[workspace]
members = [
    "rustcv",
    "rustcv-backend-avf",
    "rustcv-backend-msmf",
    "rustcv-backend-v4l2",
    "rustcv-core",
    "rustcv-simulation",
]
resolver = "2"

default-members = ["rustcv"]
